source("setup.R")
set.seed(20190421)

xlim <- 4
x <- seq(-xlim, xlim, by=0.01)
png(file.path(img_folder, "hypothesentests-dt9.png"), width=480, height=240)
df <- 9
plot(x, dt(x, df), type="l", ylab="f(x)", main=paste("Dichtefunktion der t-Verteilung\nmit", df, "Freiheitsgraden"))
Q <- qt(0.975, df)
poly_x <- c(Q, Q, x[x>Q], xlim)
polygon(poly_x, c(0, dt(Q, df), dt(x[x>Q], df), 0), col=1)
polygon(-poly_x, c(0, dt(Q, df), dt(x[x>Q], df), 0), col=1)
#poly_x <- c(-Q, -Q, x[x > -Q & x < Q], Q, Q)
#polygon(poly_x, c(0, dt(Q, df), dt(x[x > -Q & x < Q], df), dt(Q, df), 0), col=2)
text(0, 0.10, "95%", cex=1)
text(Q, 0.03, "2.5%", cex=1, pos=4)
text(-Q, 0.03, "2.5%", cex=1, pos=2)
dev.off()


png(file.path(img_folder, "hypothesentests-dt9-right.png"), width=480, height=240)
plot(x, dt(x, df), type="l", ylab="f(x)", main=paste("Kritischer Bereich bei einem einseitigen Test (rechts)"))
Q <- qt(0.95, df)
poly_x <- c(Q, Q, x[x>Q], xlim)
polygon(poly_x, c(0, dt(Q, df), dt(x[x>Q], df), 0), col=1)
text(0, 0.10, "95%", cex=1)
text(Q, 0.03, "5%", cex=1, pos=4)
dev.off()

png(file.path(img_folder, "hypothesentests-dt9-left.png"), width=480, height=240)
plot(x, dt(x, df), type="l", ylab="f(x)", main=paste("Kritischer Bereich bei einem einseitigen Test (links)"))
Q <- qt(0.95, df)  # we use a minus later, so use 0.95, not 0.05 here
poly_x <- c(Q, Q, x[x>Q], xlim)
polygon(-poly_x, c(0, dt(Q, df), dt(x[x>Q], df), 0), col=1)
text(0, 0.10, "95%", cex=1)
text(-Q, 0.03, "5%", cex=1, pos=2)
dev.off()

png(file.path(img_folder, "hypothesentests-dt12-right.png"), width=480, height=240)
plot(x, dt(x, df), type="l", ylab="f(x)", main=paste("Kritischer Bereich bei einem einseitigen Test (rechts)"))
Q <- qt(0.95, df)
poly_x <- c(Q, Q, x[x>Q], xlim)
polygon(poly_x, c(0, dt(Q, df), dt(x[x>Q], df), 0), col=1)
text(0, 0.10, "95%", cex=1)
text(Q, 0.03, "5%", cex=1, pos=4)
dev.off()

png(file.path(img_folder, "hypothesentests-dt13.png"), width=480, height=240)
df <- 13
plot(x, dt(x, df), type="l", ylab="f(x)", main=paste("Dichtefunktion der t-Verteilung\nmit", df, "Freiheitsgraden"))
Q <- qt(0.95, df)
poly_x <- c(Q, Q, x[x>Q], xlim)
polygon(poly_x, c(0, dt(Q, df), dt(x[x>Q], df), 0), col=1)
polygon(-poly_x, c(0, dt(Q, df), dt(x[x>Q], df), 0), col=1)
#poly_x <- c(-Q, -Q, x[x > -Q & x < Q], Q, Q)
#polygon(poly_x, c(0, dt(Q, df), dt(x[x > -Q & x < Q], df), dt(Q, df), 0), col=2)
text(0, 0.10, "90%", cex=1)
text(Q, 0.03, "5%", cex=1, pos=4)
text(-Q, 0.03, "5%", cex=1, pos=2)
dev.off()
