### Mathematische Symbole {#sec-math}

Das hier ist eine Übersicht aller mathematischen Schreibweisen, die in diesem Buch auftauchen werden. Man kann sie sich am besten kurz anschauen, dass man sie schonmal gesehen hat, und wieder zurückkommen, wenn die entsprechenden Notationen später wieder auftauchen.

**\(\lceil x \rceil\) und \(\lfloor x \rfloor\): Auf- und abrunden**

Diese beiden Schreibweisen bedeuten Abrunden bzw. Aufrunden der eingeklammerten Zahl \(x\). Es ist zum Beispiel \(\lfloor 2.5 \rfloor = 2\), oder \(\lceil 4 \rceil = 4\), oder \(\lceil \pi \rceil = 4\).

**\(\bar{x}\): Der Mittelwert**

Mit \(\bar{x}\) ist der Mittelwert aller \(n\) Werte \(x_i\) im Vektor \(x\) gemeint: \(\frac{1}{n} \sum_{i=1}^n x_i\). Ausgeschrieben bedeutet das: \(\bar{x} = \frac{1}{n} (x_1 + x_2 + \ldots + x_n)\). Siehe hierzu auch Kapitel \@ref(sec-summenzeichen).

**\(|x|\) und \(|\{1,5,\pi,2\} |\): Betragsstriche**

Mit Betragsstrichen sind zweierlei Dinge gemeint:

Steht innerhalb der Betragsstriche eine einzelne Zahl, so wie \(x\) oder \(-2\), so wird mit dem Betrag ihr absoluter Wert bezeichnet. Dieser Wert ist immer positiv. \(|x|\) ist also genau gleich wie \(x\), falls \(x\geq 0\) ist, und \(|x| = -x\), falls \(x <0 \) ist. Ein Beispiel dafür: Sehen wir \(| -10 |\), so ist \(x\), also \(-10\), kleiner als 0, und \(|-10| = - (-10) = 10\).

Steht innerhalb der Betragsstriche aber eine Menge an Zahlen (man erkennt das an den geschweiften Klammern), so deuten die Betragsstriche an, dass uns die Anzahl der Elemente interessiert. Es ist also \(| \{1,5,\pi, 2\} | = 4\).

**\(N!\): Fakultät**

Das Ausrufezeichen steht für die Fakultät einer Zahl, womit gemeint ist, dass alle Zahlen von 1 bis \(N\) nacheinander multipliziert werden. Es ist zum Beispiel \(5! = 1 \cdot 2 \cdot 3 \cdot 4 \cdot 5 = 120\).

Ein Sonderfall ist die Fakultät von Null, die als 1 definiert wird: \(0! = 1\).

**\({n \choose k}\): Binomialkoeffizient**

Der Binomialkoeffizient wird in der Kombinatorik verwendet. Wenn wir eine Menge von \(n\) Objekten haben, und uns \(k\) Objekte daraus auswählen, so gibt es \(n \choose k\) Möglichkeiten, das zu tun. Berechnen lässt er sich durch die Formel \({N\choose k} = \frac{N!}{(N-k)!\cdot k!}\). Beim Lotto gibt es z.B. \(n=49\) Zahlen, aus denen \(k=6\) ausgewählt werden. Dafür gibt es \({49 \choose 6} = 13983816\) verschiedene Möglichkeiten.