## Häufigkeitstabellen {#sec-haeufigkeitstabellen}

Häufigkeitstabellen fassen Daten in einer Tabelle zusammen, die für jede mögliche Ausprägung zeigt, wie oft diese Ausprägung vorgekommen ist. Diese Tabellen sind nur für diskrete Daten (s. Kap. \@ref(merkmals-und-skalentypen)) sinnvoll, da bei stetigen Daten jede Beobachtung einen anderen Wert hat, und die Tabelle dann nichts zusammenfassen würde. Bei gruppierten stetigen Daten kann aber eine Tabelle erstellt werden.

Häufigkeitstabellen sind meist ein erster Schritt in der Datenanalyse, da sie die Grundlage für z.B. Balkendiagramme, Lorenzkurven oder Verteilungsfunktionen bilden.

Man unterscheidet **absolute** und **relative** Häufigkeiten. Absolute Häufigkeiten bezeichnet man für die verschiedenen Ausprägungen mit \(h_i\). Sie sind einfach die ausgezählten Daten für jede Ausprägung. Relative Häufigkeiten, die wir \(f_i\) nennen, sind die *Anteile*, die auf jede Ausprägung fallen.

Dann gibt es noch **kumulierte** Häufigkeiten, die wir \(F_i\) nennen. In ihr werden die relativen Häufigkeiten aufsummiert. Die kumulierte Häufigkeitstabelle wird meist nur mit relativen Häufigkeiten gebildet - mit absoluten Häufigkeiten findet sie eigentlich nirgends Verwendung. Ein Beispiel veranschaulicht das wahrscheinlich am besten.

Wir packen einen Block und einen Bleistift ein, und machen uns auf den Weg zum Campus, um 80 Studenten zu befragen. Uns interessiert, in welchem Semester sie sich so befinden. Da gerade Wintersemester ist, erwarten wir mehr Studenten in "ungeraden" Semestern, also im ersten, dritten, etc.

Nach einem anstrengenden Tag zählen wir die Daten aus. 20 unserer 80 befragten Studenten - also ein Viertel - sind im ersten Semester. Die restlichen Antworten sind in der folgenden Tabelle zusammengefasst. Die Spalte \(h_i\) zeigt die absolute Anzahl an Antworten für jede Semesterzahl (von 1 bis 7). In der Spalte \(f_i\) ist die relative Häufigkeit, also die Spalte \(h_i\) geteilt durch \(n=80\). In der letzten Spalte ist die kumulierte Häufigkeit \(F_i\), hier werden die Elemente der Spalte \(f_i\) schrittweise aufsummiert.

(ref:tab-haeufgk-h1) Semester \(i\)

(ref:tab-haeufgk-h2) \(h_i\)

(ref:tab-haeufgk-h3) \(f_i\)

(ref:tab-haeufgk-h4) \(F_i\)

```{r}
tbl <- tibble(
    "(ref:tab-haeufgk-h1)" = c(1, 2, 3, 4, 5, 6, 7),
    "(ref:tab-haeufgk-h2)" = c(20, 4, 13, 9, 21, 5, 8),
    "(ref:tab-haeufgk-h3)" = c(0.25, 0.05, 0.1625, 0.1125, 0.2625, 0.0625, 0.1),
    "(ref:tab-haeufgk-h4)" = c(0.25, 0.3, 0.4625, 0.575, 0.8375, 0.9, 1)
)

if(knitr::is_html_output()){
    knitr::kable(tbl)
} else if(knitr::is_latex_output()){
    knitr::kable(tbl, format='latex', booktabs=TRUE, linesep="\\addlinespace", longtable=FALSE) %>%
        kableExtra::kable_styling(latex_options="striped")
}
```