### \(\chi^2\)-Verteilung {#sec-chisq-verteilung}

#### Idee {-}

Die \(\chi^2\)-Verteilung wird eigentlich nur für einige Hypothesentests verwendet, insbesondere für den Unabhängigkeitstest für Kontingenztabellen. In der "freien Wildbahn", also zum Modellieren irgendwelcher erhobenen Daten, trifft man sie quasi nie an. Aus diesem Grund sind viele Details dieser Verteilung (Erwartungswert, Dichte, und Varianz) eher unwichtig - nur die Verteilungsfunktion ist interessant, da mit ihr das 95%-Quantil (die wichtige kritische Schranke für Hypothesentests) bestimmt werden kann.

#### Parameter {-}

Die \(\chi^2\)-Verteilung hat einen Parameter, nämlich die Anzahl der Freiheitsgrade, \(df\). Man notiert eine \(\chi^2\)-verteilte Zufallsvariable \(X\) mit \(df\) Freiheitsgraden als

\[ X \sim \chi^2 (df) \]

Abbildung \@ref(fig:verteilungen-chisq-verteilung-dichte-und-verteilungsfunktion) zeigt einige beispielhafte \(\chi^2\)-Verteilungen

(ref:verteilungen-chisq-v-d-u-v-caption) Dichte- und Verteilungsfunktion der \(\chi^2\)-Verteilung für verschiedene beispielhafte Freiheitsgrade.

```{r verteilungen-chisq-verteilung-dichte-und-verteilungsfunktion, fig.width=6, fig.height=8, out.width="75%", fig.cap="(ref:verteilungen-chisq-v-d-u-v-caption)"}
par(mfrow=c(2,1))

x <- seq(0.01, 10, by=0.01)
dfs <- c(2, 3, 4, 5)
plot(x, dchisq(x, 1), type="l", col=1, main="Dichtefunktionen der Chi-Quadrat-Verteilung", ylab="f(x)", ylim=c(0,1), lwd=2)
for(i in seq_along(dfs)){
    col <- i+1
    df <- dfs[i]
    lines(x, dchisq(x, df), col=col, lwd=2, lty=i+1)
}
legend("topright", lty=1:5, legend=paste(c(1, dfs), c("Freiheitsgrad", rep("Freiheitsgrade", length(dfs)))), col=1:(1+length(dfs)), lwd=2)

x <- seq(0.01, 10, by=0.01)
dfs <- c(2, 3, 4, 5)
plot(x, pchisq(x, 1), type="l", col=1, main="Verteilungsfunktionen der Chi-Quadrat-Verteilung", ylab="F(x)", ylim=c(0,1), lwd=2)
for(i in seq_along(dfs)){
    col <- i+1
    df <- dfs[i]
    lines(x, pchisq(x, df), col=col, lwd=2, lty=i+1)
}
legend("bottomright", lty=1:5, legend=paste(c(1, dfs), c("Freiheitsgrad", rep("Freiheitsgrade", length(dfs)))), col=1:(1+length(dfs)), lwd=2)
```

#### Träger {-}

Der Träger der \(\chi^2\)-Verteilung ist \(\mathbb{R}^+\), die positiven reellen Zahlen.

#### Erwartungswert, Varianz und Dichte {-}

Da mit der \(\chi^2\)-Verteilung eigentlich nie Daten modelliert werden, braucht man eigentlich weder die Dichte, noch den Erwartungswert oder die Varianz kennen. Der Vollständigkeit halber sei sie hier trotzdem genannt: Der Erwartungswert für eine \(\chi^2\)-verteilte Zufallsvariable \(X\) mit \(df\) Freiheitsgraden ist \(\mathbb{E}(X) = df\), und ihre Varianz ist \(\mathbb{V}(X)= 2\cdot df\).

#### Verteilungsfunktion {-}

Wie oben schon erwähnt, ist für die \(\chi^2\)-Verteilung eigentlich nur die Verteilungsfunktion, und dort auch meistens nur das 95%-Quantil als Spezialfall, interessant.

Die Formel für die Verteilungsfunktion ist sehr aufwändig zu notieren und auszurechnen, weshalb es auch hier eine Verteilungstabelle gibt (s. Kap. \@ref(sec-tabelle-chisq-verteilung)), an der man die wichtigsten Werte einfach ablesen kann. Auch hier gilt es, einfach ein wenig Übung im Umgang mit der Tabelle zu erhalten, damit man die gewünschten Quantilswerte ohne Zeitverlust und Leichtsinnsfehler richtig und schnell ablesen kann.