### Gepaarter \(t\)-Test: Vorher/Nachher-Mittelwertsvergleich {#sec-gepaarter-t-test}

Der *gepaarte* t-Test wird immer dann verwendet, wenn man zwar zwei Stichproben (d.h. zwei "Gruppen") hat, diese aber *verbunden* sind. Verbunden bedeutet in diesem Fall, dass jeder Beobachtung aus der ersten Gruppe direkt eine aus der zweiten Gruppe zugeordnet werden kann, die beiden Beobachtungen gehören also zusammen. In den meisten Fällen ist das der Fall, wenn man einen vorher/nachher-Vergleich machen möchte. Andere Fälle, in denen die Beobachtungen zweier Gruppen "zusammengehören", also verbunden sind, sind zum Beispiel Zwillingsstudien, in denen je ein Zwilling in eine Gruppe kommt, und dann Unterschiede bezüglich Verhalten oder Eigenschaften getestet werden.

Als Beispiel eines vorher/nachher-Vergleichs misst man etwa bei 9 Personen den Blutdruck, führt sie dann 30 Minuten durch eine Meditation, und misst danach *an denselben Personen* nochmal den Blutdruck.

In diesem Beispiel könnten die Daten dann wie folgt aussehen:

| Person \(x_i\) | Blutdruck vorher | Blutdruck nachher |
| -------------- | ---------------- | ----------------- |
| 1              | 130              | 124               |
| 2              | 145              | 142               |
| 3              | 151              | 138               |
| 4              | 143              | 143               |
| 5              | 129              | 122               |
| 6              | 138              | 141               |
| 7              | 143              | 140               |
| 8              | 113              | 108               |
| 9              | 133              | 127               |

Wir möchten nun zum Signifikanzniveau \(\alpha=0.1\) testen, ob diese Personen nach der 30-minütigen Meditation einen niedrigeren Blutdruck haben, ob sich also der durchschnittliche Blutdruck gesenkt hat.

Das Schöne an einer *gepaarten* Stichprobe ist nun, dass wir uns eines Tricks bedienen können, nach dem wir dann einfach den bekannten Einstichproben-t-Test (s. Kap. \@ref(sec-einstichproben-t-test)) verwenden können:

Da die beiden Gruppen *verbunden* sind, es also jeweils dieselbe Person in der vorher- bzw. nachher-Gruppe ist, können wir für jede Person die Differenz der beiden Messungen berechnen. Wir fügen eine neue Spalte an die Tabelle von eben an, in der wir einfach "nachher minus vorher" rechnen:

| Person \(x_i\) | Blutdruck vorher | Blutdruck nachher | Differenz / "Effekt" |
| -------------- | ---------------- | ----------------- | -------------------- |
| 1              | 130              | 124               | -6                   |
| 2              | 145              | 142               | -3                   |
| 3              | 151              | 138               | -13                  |
| 4              | 143              | 143               | 0                    |
| 5              | 129              | 122               | -7                   |
| 6              | 138              | 141               | +3                   |
| 7              | 143              | 140               | -3                   |
| 8              | 113              | 108               | -5                   |
| 9              | 133              | 127               | -6                   |

Wir rechnen "nachher minus vorher", und nicht "vorher minus nachher", damit eine negative Zahl, z.B. -6, darauf hindeutet, dass der Blutdruck nach der Meditation *gesunken* ist.

Die letzte Spalte beinhaltet nun also den "Effekt" der Meditation (falls es einen gibt). Die erste Person hatte zum Beispiel nach der Meditation einen um 6 Punkte niedrigeren Blutdruck als vorher.

Der bequeme und erfreuliche Effekt dieser Nebenrechnung ist jetzt, dass wir die Vorher- bzw. Nachher-Messungen wegwerfen können, und nur noch mit der Differenz weiterarbeiten. Da das nur noch eine einzige Variable ist, können wir mit ihr den bereits bekannten Einstichproben-t-Test (s. Kap. \@ref(sec-einstichproben-t-test)) durchführen.

Die Hypothesen werden dann abhängig davon gebildet, welchen Effekt man testen möchte. Wenn wir - wie in diesem Beispiel - nachweisen möchten, dass die Nachher-Messung niedriger ist, dann wäre die Alternativhypotese demnach, dass der Mittelwert der eben berechneten Differenzen *kleiner als Null* ist, also \(H_1: \mu < 0\). (Warum das so ist, wird in Kapitel \@ref(sec-h0-h1) erklärt).

Ab jetzt können wir also den Einstichproben-t-Test durchführen, und brauchen hier daher kein neues Vorgehen, keine separate Erklärung mehr. Die Daten, mit denen wir den Einstichproben-t-Test durchführen, sind:

- \(H_0: \mu \geq 0\)
- \(H_1: \mu < 0\)
- Signifikanzniveau: \(\alpha = 0.1\)
- \(x = (-6, -3, -13, 0, -7, +3, -3, -5, -6)\). Das ist die letzte Spalte der Tabelle oben, unsere "neue" Stichprobe, nämlich die der Differenzen von vorher zu nachher.

Damit können wir direkt in Schritt 5 der Abfolge beim Hypothesentest einsteigen, dem Berechnen der Prüfgröße. Dieser und alle weiteren Schritte kann man nun genauso durchführen wie im Kapitel \@ref(sec-einstichproben-t-test) zum Einstichproben-t-Test erklärt.

#### Ergebnis {-}

Wer diese Aufgabe selbst zuende rechnen und nachprüfen möchte, für den fasse ich hier die Ergebnisse kurz zusammen. Das Vorgehen ist wie gesagt in Kapitel \@ref(sec-einstichproben-t-test) detailliert beschrieben.

- Mittelwert: \(\bar{x} = -4.444\)
- Standardabweichung: \(s = 4.531\)
- Stichprobengröße: \(n = 9\)

#### Schritt 5: Prüfgröße berechnen {-}

\[T = \sqrt{n} \cdot \frac{\bar{x} \, - \, \mu_0}{s} = \sqrt{9} \cdot \frac{-4.444 \, - \, 0}{4.531} = -2.942 \]

#### Schritt 6: Verteilung der Prüfgröße bestimmen {-}

\[T \sim t(8) \]

#### Schritt 7: Kritischen Bereich (oder p-Wert) berechnen {-}

Vorsicht: In dieser Aufgabe ist das Signifikanzniveau \(\alpha\) nicht 0.05, wie es normalerweise ist, sondern 0.1.

Der kritische Bereich ist das linke Ende der t-Verteilung, die "niedrigen" Zahlen, denn die Alternativhypothese zielt auf Bereiche ab, in denen die Differenz stark negativ ist.

Für die kritische Schranke brauchen wir das 10%-Quantil der t-Verteilung mit 8 Freiheitsgraden. Laut t-Tabelle (s. Kap. \@ref(sec-tabelle-t-verteilung)) ist es -1.397.

Der kritische Bereich, in dem wir die Nullhypothese ablehnen, sind also alle Werte für \(T\), die kleiner als -1,397 sind.

#### Schritt 8: Testentscheidung treffen {-}

Hier ist \(T=-2.942\), und der kritische Bereich ist alles was kleiner als -1,397 ist. Daher liegt die Prüfgröße im kritischen Bereich, und somit können wir die Nullhypothese bei dieser Untersuchung ablehnen.